# Generated by Django 5.2.5 on 2025-11-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image_url",
            field=models.URLField(max_length=1000),
        ),
    ]
