# Generated by Django 5.2.6 on 2025-10-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "voter_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_number", models.IntegerField()),
                ("street_name", models.TextField()),
                ("apartment_number", models.TextField(blank=True)),
                ("zip_code", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("registration_date", models.DateField()),
                ("party_affiliation", models.CharField(max_length=2)),
                ("precinct", models.IntegerField()),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
