# Generated by Django 5.2.6 on 2025-10-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voter",
            name="voter_ID",
        ),
        migrations.AddField(
            model_name="voter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
