# Generated by Django 5.2.5 on 2025-09-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_insta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
