# Generated by Django 5.2.5 on 2025-09-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_insta", "0002_article_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("profile_image_url", models.URLField(blank=True)),
                ("bio_text", models.TextField(blank=True)),
                ("join_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
