# Generated by Django 5.2.6 on 2025-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_insta", "0005_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
