# Generated by Django 5.2.6 on 2025-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_insta", "0006_profile_image_file_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image_file",
        ),
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
