# Generated by Django 5.2.6 on 2025-10-15 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_insta", "0007_remove_profile_image_file_photo_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(upload_to=""),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "follower_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_profile",
                        to="mini_insta.profile",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="mini_insta.profile",
                    ),
                ),
            ],
        ),
    ]
