# Generated by Django 5.2.5 on 2025-11-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revize", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
